package com.gifiti.api.model;

import com.gifiti.api.model.enums.Visibility;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Unit test for the {@code accessCode} field added to the {@link Wishlist}
 * entity in feature 008 (T1). Per ADR 0008 § Decision E (plaintext storage)
 * and § Decision F (4-digit numeric, leading zeros allowed): the field is a
 * nullable String on the document, non-null only when {@code visibility ==
 * PRIVATE}.
 *
 * <p>This is a model-level structural test — it pins the field's existence
 * and Lombok-generated getter/setter so subsequent tasks (T3 + T4) can rely
 * on it without re-asserting field shape.
 *
 * <p>Per `architecture-conventions.md § Engineering Workflow` — RED-GREEN-
 * REFACTOR. This test was written before the field was added; it failed to
 * compile (no symbol `getAccessCode`) before T1's GREEN step.
 */
class WishlistAccessCodeFieldTest {

    @Test
    @DisplayName("Wishlist exposes a nullable accessCode field via Lombok getter/setter")
    void accessCodeFieldExistsAndAllowsNullAndNonNull() {
        Wishlist wishlist = Wishlist.builder()
                .ownerUserId("user-1")
                .title("Test")
                .visibility(Visibility.PRIVATE)
                .build();

        // Default (not set on builder) is null — matches Decision F: code is
        // generated by service layer (T3), not on entity construction.
        assertThat(wishlist.getAccessCode()).isNull();

        // Setter allows a 4-digit String (including leading zero).
        wishlist.setAccessCode("0042");
        assertThat(wishlist.getAccessCode()).isEqualTo("0042");

        // Setter allows null again (transition back to PUBLIC clears the code, T4).
        wishlist.setAccessCode(null);
        assertThat(wishlist.getAccessCode()).isNull();
    }

    @Test
    @DisplayName("Wishlist builder accepts accessCode")
    void builderAcceptsAccessCode() {
        Wishlist wishlist = Wishlist.builder()
                .ownerUserId("user-1")
                .title("Test")
                .visibility(Visibility.PRIVATE)
                .accessCode("1234")
                .build();

        assertThat(wishlist.getAccessCode()).isEqualTo("1234");
    }
}
